language: node_js
node_js:
  - "6"

sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - npm install
  - bower install

script:
  - ember build --prod
deploy:
  provider: surge
  project: ./dist
  domain: justinadrew.com
  on: master
